
-- exclui as sequências
DROP SEQUENCE SQ_XCAVE_MATRICULA;
DROP SEQUENCE SQ_XCAVE_DOCUMENTO;
DROP SEQUENCE SQ_XCAVE_DEPENDENTE;

-- limpa os registros das tabelas
TRUNCATE TABLE T_XCAVE_DOCUMENTO;
TRUNCATE TABLE T_XCAVE_DEPENDENTE;
TRUNCATE TABLE T_XCAVE_COLABORADOR;
TRUNCATE TABLE T_XCAVE_LOGIN;

-- cria sequência para a matrícula
CREATE SEQUENCE SQ_XCAVE_MATRICULA MAXVALUE 999999 MINVALUE 1000 NOCACHE;

-- cria sequência para o código do documento
CREATE SEQUENCE SQ_XCAVE_DOCUMENTO MAXVALUE 999999 NOCACHE;

-- cria sequência para o código do dependente
CREATE SEQUENCE SQ_XCAVE_DEPENDENTE MAXVALUE 999999 NOCACHE;

-- insere login do administrador
INSERT INTO T_XCAVE_LOGIN (CD_MATRICULA,NM_EMAIL,NM_SENHA,NM_APELIDO,ST_CADASTRO) VALUES (SQ_XCAVE_MATRICULA.NEXTVAL,'admin@fiap.com.br','fiap123','ADMIN',1);

-- insere login do novo colaborador para cadastro
INSERT INTO T_XCAVE_LOGIN (CD_MATRICULA,NM_EMAIL,NM_SENHA,NM_APELIDO,ST_CADASTRO) VALUES (SQ_XCAVE_MATRICULA.NEXTVAL,'joao@fiap.com.br','joao123','JOAO',0);
INSERT INTO T_XCAVE_LOGIN (CD_MATRICULA,NM_EMAIL,NM_SENHA,NM_APELIDO,ST_CADASTRO) VALUES (SQ_XCAVE_MATRICULA.NEXTVAL,'maria@fiap.com.br','maria123','MARIA',0);
INSERT INTO T_XCAVE_LOGIN (CD_MATRICULA,NM_EMAIL,NM_SENHA,NM_APELIDO,ST_CADASTRO) VALUES (SQ_XCAVE_MATRICULA.NEXTVAL,'pedro@fiap.com.br','pedro123','PEDRO',0);

-- commit das informações
COMMIT;